---

# Author: Jacob M
# Last edited on: 1/23/2024
# Educational purposes only

# Docker install with configuration and mounting. For Ubuntu 22.04 Server

- hosts: docker
  become: true
  tasks:
  - name: Install all packages needed for docker host
    apt:
      pkg:
        - docker
        - docker-compose
        - cifs-utils
        - smbclient
        - samba
      state: latest
      update_cache: true

  - name: Check for the docker user
    ansible.builtin.stat:
      path: /home/torrent
    register: dockerUser

  - name: Make the docker user
    ansible.builtin.user:
      name: torrent
      comment: docker user
      uid: 666
    when: dockerUser.stat.exists == False
 
  - name: Check the mount of docker servers
    ansible.builtin.stat:
      path: /mnt/Media
    register: mount

  - name: Mounting network drives
    shell: |
      mkdir /mnt/Media                                                       #Variable, could reference variable file if needed
      mount -t cifs //192.168.0.10/Media /mnt/Media -o username=server       #Variable, could reference variable file if needed
    when: mount.stat.exists == False

  - name: Docker dir check
    stat:
      path: /home/torrent/docker_torrents
    register: dockerCompose

  - name: Creating Docker environment
    shell: |
      mkdir /home/torrent/docker_torrents
      touch /home/torrent/docker_torrents/docker-compose.yaml
      chmod 755 /home/torrent/docker_torrents
      chown torrent /home/torrent/*
      chown torrent /home/torrent/docker_torrents/*
      mkdir /home/torrent/git
    when: dockerCompose.stat.exists == False

  - name: Docker dir check
    stat:
      path: /home/torrent/docker
    register: docker

  - name: Creating Docker config environment
    shell: |
      mkdir /home/torrent/docker
      mkdir /home/torrent/docker/radarr
      mkdir /home/torrent/docker/sonarr
      mkdir /home/torrent/docker/qbittorrent
      mkdir /home/torrent/docker/jackett
      mkdir /home/torrent/docker/uptime-kuma-data
      mkdir /home/torrent/docker/heimdall
      chown torrnet /home/torrent/docker/*
      chown torrent /home/torrent/docker
    when: docker.stat.exists == False

  - name: Update git repo for scripts
    ansible.builtin.git:
      repo: 'https://github.com/jacobmyers98/Automation-Scripts'
      dest: /home/torrent/git
      update: yes

  - name: Create a cron job entry
    cron:
      name: backup service
      special_time: monthly
      job: "/home/torrent/git/Automation-Scripts/simple_server-backup"

  - name: Creating Docker-Compose file                                            #Variable, can change to your docker-compose.yml file if needed
    copy:
      dest: /home/torrent/docker_services/docker-compose.yaml
      content: |
        version: "3.8"
        services:
          radarr:
            image: lscr.io/linuxserver/radarr
            networks:
              - network1
            ports:
              - "7878:7878" # port mapping
            volumes:
              - /mnt/Media:/mnt/Media
              - /home/torrent/docker/radarr/config:/config
              - /downloads:/downloads
            environment:
              TZ: America/Denver
              PUID: 666 # set this to the UID of your user
              PGID: 666 # set this to the GID of your user
            restart: unless-stopped

          sonarr:
            image: lscr.io/linuxserver/sonarr
            networks:
              - network1
            ports:
              - "8989:8989" # port mapping
            volumes:
              - /mnt/Media:/mnt/Media
              - /home/torrent/docker/sonarr/config:/config
              - /downloads:/downloads
            environment:
              TZ: America/Denver
              PUID: 666 # set this to the UID of your user
              PGID: 666 # set this to the GID of your user
            restart: unless-stopped

          qbittorrent:
            image: lscr.io/linuxserver/qbittorrent
            networks:
              - network1
            ports:
              - 8080:8080
              - 6881:6881
              - 6881:6881/udp
            environment:
              - PUID: 666
              - PGID: 666
              - TZ: America/Denver
              - WEBUI_PORT: 8080
            volumes:
              - /mnt/Media:/mnt/Media
              - /home/torrent/docker/qbittorrent/config:/config
              - /downloads:/downloads
            restart: unless-stopped

          jackett:
            image: lscr.io/linuxserver/jackett
            networks:
              - network1
            ports:
              - 9117:9117
            environment:
              - PUID: 666
              - PGID: 666
              - TZ: America/Denver
            volumes:
              - /mnt/Media:/mnt/Media
              - /home/torrent/docker/jackett/config:/config
              - /downloads:/downloads
            restart: unless-stopped

          uptime-kuma:
            image: louislam/uptime-kuma
            container_name: uptime-kuma
            networks:
              - network1
            environment:
              - PUID: 666
              - PGID: 666
              - TZ=America/Denver
            volumes:
            - /home/torrent/docker/uptime-kuma-data/config:/uptime-kuma-data
            ports:
            - 3001:3001  # <Host Port>:<Container Port>
            restart: unless-stopped

          heimdall:
            image: linuxserver/heimdall
            container_name: heimdall
            networks:
              - network1
            environment:
              - PUID: 666
              - PGID: 666
              - TZ=America/Denver
            volumes:
              - /home/torrent/docker/heimdall/config:/config
            ports:
              - 443:443
            restart: unless-stopped

        networks:
          network1:
            name: docker0
            driver: bridge
            external: false

  - name: apt update
    apt:
      upgrade: yes
