---

# Author: Jacob M
# Last edited on: 2/5/2024
# Educational purposes only

# Microk8s install with configuration and mounting. For Ubuntu 22.04 Server

- hosts: all
  become: true
  tasks:
  - name: Install all packages for the host
    apt:
      pkg:
        - docker
        - cifs-utils
        - smbclient
        - samba
      state: latest
      update_cache: true
    community.general.snap:
      name: microk8s
      classic: yes

  - name: Check for the Docker user
    ansible.builtin.stat:
      path: /home/server
    register: dockerUser

  - name: Make the K8 user
    ansible.builtin.user:
      name: server
      comment: docker user
      uid: 666
    when: dockerUser.stat.exists == False
 
  - name: Check the mount of the network Raid
    ansible.builtin.stat:
      path: /mnt/Media
    register: mount

  - name: Mounting network Raid
    shell: |
      mkdir /mnt/Media                                                       #Variable, could reference variable file if needed
      mount -t cifs //192.168.0.10/Media /mnt/Media -o username=server       #Variable, could reference variable file if needed
    when: mount.stat.exists == False

  - name: Creating K8 environment (installing Microk8s)
    shell: |
      sudo swapoff -a
      sudo usermod -a -G microk8s server
      sudo chown -f -R server ~/.kube
      su - server
      microk8s start
      microk8s enable dashboard
      microk8s enable dns
      microk8s enable ingress
      microk8s kubectl get all --all-namespaces
      microk8s dashboard-proxy &

  - name: Starting the Cluster
    shell: microk8s add-node
    register: shell_result

  - name: Creating K8s file (deployment)
    copy:
      dest: /home/server/K8-Deployment.yaml
      content: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: radarr
        spec:
          containers:
          - name: radarr
              image: lscr.io/linuxserver/radarr

  - name: apt update
    apt:
      upgrade: yes

  - debug:
      var: shell_result.stdout_lines

