---

# Author: Jacob M
# Last edited on: 6/23/2025
# Educational purposes only
# ansible-playbook -Kb -i inventory.ini ./K8s-trivy-install.yaml --connection=localhost

# k8s trivy install and configuration. For Ubuntu 22.04 Server


- name: Deploy trivy vulnerability scanner with helm
  hosts: all
  become: yes
  tasks:
    - name: Add Trivy Helm repository & deploy it
      shell: |
        helm repo add aqua https://aquasecurity.github.io/helm-charts/
        helm repo update
        helm install trivy-operator aqua/trivy-operator \
           --namespace trivy-system \
           --create-namespace \
           --set compliance.enabled=true \
           --set metrics.enabled=true \
           --set prometheus.serviceMonitor.enabled=true

# Commmands
# kubectl delete clustercompliancereport --all trigger rescan
# kubectl get vulnerabilityreports --all-namespaces -o wide
# kubectl get configauditreports --all-namespaces -o wide
# kubectl logs -n trivy-system deployment/trivy-operator
