---

# Author: Jacob M
# Last edited on: 1/23/2024
# Educational purposes only

# ansible-playbook Playbooks/simple_update.yml
# ansible playbook to update docker containers and pterodactyl containers
- hosts: all
  become: true
  tasks:
  - name: apt update
    apt:
      upgrade: yes

  - name: check the mount of servers
    ansible.builtin.stat:
      path: /mnt/Media
    register: mount

  - name: Mounting network drives
    shell: |
      mkdir /mnt/Media                                                       #Variable, could reference variable file if needed
      mount -t cifs //192.168.0.10/Media /mnt/Media -o username=server       #Variable, could reference variable file if needed
    when: mount.stat.exists == False

  - name: update git repo for scripts
    ansible.builtin.git:
      repo: 'https://github.com/jacobmyers98/Automation-Scripts'
      dest: /home/torrent/git
      update: yes

  - name: check pterodactyl is installed
    ansible.builtin.stat:
      path: /var/www/pterodactyl
    register: p_alive

  - name: update pterodactyl if alive
    script: /home/torrent/git/Automation-Scripts/pterodactyl_update
    when: p_alive.stat.exists

  - name: check docker-compose is installed
    ansible.builtin.stat:
      path: /home/torrent/docker_torrents
    register: docker_alive

  - name: update docker-compose if alive
    shell: |
      cd /home/torrent/docker_torrents
      docker-compose pull
      docker-compose up -d
    when: docker_alive.stat.exists
