---
# ansible-playbook Playbooks/simple_update.yml
- hosts: all
  become: true
  tasks:
  - name: apt update
    apt:
      upgrade: yes

  - name: check the mount of servers
    ansible.builtin.stat:
      path: /mnt/Media
    register: mount

  - name: Mounting network drives
    shell: mkdir /mnt/Media                                                       #Variable, could reference variable file if needed
    shell: mount -t cifs //192.168.0.10/Media /mnt/Media -o username=server       #Variable, could reference variable file if needed
    when: mount.stat.exists == False

  - name: check pterodactyl is installed
    ansible.builtin.stat:
      path: /var/www/pterodactyl
    register: p_alive

  - name: update pterodactyl if alive
    shell: cd /var/www/pterodactyl
    shell: php artisan down
    shell: curl -L https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz | tar -xzv
    shell: chmod -R 755 storage/* bootstrap/cache
    shell: composer install --no-dev --optimize-autoloader
    shell: php artisan view:clear
    shell: php artisan config:clear
    shell: php artisan migrate --seed --force
    shell: chown -R www-data:www-data /var/www/pterodactyl/*
    shell: php artisan queue:restart
    shell: php artisan up
    shell: systemctl stop wings
    shell: curl -L -o /usr/local/bin/wings "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")"
    shell: chmod u+x /usr/local/bin/wings
    shell: systemctl restart wings   
    when: p_alive.stat.exists

  - name: check docker-compose is installed
    ansible.builtin.stat:
      path: /home/torrent/docker_torrents
    register: docker_alive

  - name: update docker-compose if alive
    shell: cd /home/torrent/docker_torrents
    shell: docker-compose up -d
    when: docker_alive.stat.exists
