---
# ansible-playbook Playbooks/simple_update.yml
- hosts: all
  become: true
  tasks:
  - name: apt update
    apt:
      upgrade: yes
      update_chache: yes

  - name: check pterodactyl is installed
    ansible.builtin.stat:
      path: /var/www/pterodactyl
    register: p_alive

  - name: update pterodactyl if alive
    command: 
    command: 
    command:
    command:
    command:
    command:
    command:
    command:
    command:
    when: p_alive.stat.exists

  - name: check docker-compose is installed
    ansible.builtin.stat:
      path: /home/torrent/docker_torrents
    register: docker_alive

  - name: update docker-compose if alive
    command: cd /home/torrent/docker_torrents
    command: docker-compose up -d
    when: docker_alive.stat.exists
