---

# Author: Jacob M
# Last edited on: 2/5/2024
# Educational purposes only

# Microk8s install with configuration and mounting. For Ubuntu 22.04 Server

- hosts: all
  become: true
  tasks:
  - name: testy
