- hosts: all
  become: false
  tasks:
  - name: Install all packages for the host
    shell:
      cmd: "echo $HOME"
    register: VAR

  - name: Show result content only
    shell: mkdir {{ VAR }}/test
