apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-metrics
  namespace: kube-system
  labels:
    release: prometheus  # Change this if your Prometheus release is named differently
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: metrics
    interval: 15s

---

apiVersion: v1
kind: Service
metadata:
  name: cilium-metrics
  namespace: kube-system
  labels:
    k8s-app: cilium
spec:
  selector:
    k8s-app: cilium
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
